version: "3"
services:
  filter_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: filter_app_image
    container_name: filter_app_container
    restart: unless-stopped
    env_file: docker.env
    ports:
      - "80:80"
    volumes:
        - ./src:/usr/src/app/src
        - productImages:/root/src/public/images
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: project_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jacek.luczak@outlook.com
      PGADMIN_DEFAULT_PASSWORD: dostęp_PODGLAD_ZARZADZANIE_BAZA_2021
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:postgres
    networks:
      - app-network




networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  pgdata:
  productImages:
  pgadmin-data:

